### ISSUE TITLE
JSON support

### ISSUE THREAD

**Issue by kopax** [airbnb/polyglot.js#107]
it would be nice to be able to import json,file with such kind of content : 

```json
{
  "app.component.navigation.navToolbar.blogging": "Blogging",
  "app.component.navigation.navToolbar.profile": "Profile",
  "app.component.navigation.navToolbar.settings": "Settings",
  "app.component.platform.schemaVersions.title": "Schema Version |||| Schemas Version"
}
```

Did anybody ever did that before ?

**Comment by ljharb** [comment]
You can already do that; requiring a json file gives you an object, and that can be passed directly into `.extend`

**Comment by kopax** [comment]
I can't decide between `polyglot` and `react-intl`.

I like the fact to use `babel-plugin-react-intl` and to scan for the used key and export a json file before using it in our app.

This way we can make many package that just export their json on distribution.

is there an equivalent we can use for polyglot ?

**Comment by ljharb** [comment]
Scanning for used keys is something you can always do outside this library; this library isn’t solving that use case directly (but airbnb does this, so it’s possible).

You can use any form of static analysis, combined with a linter rule, to statically extract all used keys.
