### ISSUE TITLE
Modernize the code base

### ISSUE THREAD

**Issue by NeoLegends** [airbnb/polyglot.js#109]
Hey!

I'm seeing you're using quite an old JS style and using modules that you really wouldn't need to be using ([has](https://www.npmjs.com/package/has) and [warning](https://www.npmjs.com/package/warning)), for example). Whats your stance on modernizing the codebase of polyglot and reducing its dependencies? :)

**Comment by ljharb** [comment]
The `has` and `warning` packages would be used even if we were using ES2018, so I'm not sure what you mean by "modernizing" there.

Separately, dependencies are a good thing, and reducing them is rarely an improvement.

**Comment by NeoLegends** [comment]
> Separately, dependencies are a good thing, and reducing them is rarely an improvement.

This is arguably untrue. Memes about the size of the `node_modules` folder don't appear out of nowhere, and reducing the amount of dependencies generally correlates with a smaller output build size in frontend projects.

**Comment by ljharb** [comment]
Tree-shaking works identically as well with CJS as it does with ESM; regardless, no parts of those two deps are unused (except the parts that are compiled out with `NODE_ENV` is "production").

**Comment by mreinstein** [comment]
I've got a PR which adds support for es modules, and should work with modern bundlers out-of-the-box #125

**Comment by ljharb** [comment]
Node does not yet support ES Modules unflagged; and as such, there's no point in adding support for it in a package.

**Comment by mreinstein** [comment]
@ljharb es modules are not supported in node, that is correct.  The goal is to enable front end bundlers to use module imports. For example, webpack and rollup will be able to include the module directly.  A good writeup: https://github.com/rollup/rollup/wiki/pkg.module

**Comment by ljharb** [comment]
There’s no need for them to do that since they already can consume CJS.

Additionally, tree shaking works just fine with CJS (webpack and friends just haven’t bothered to add it), and there’s nothing in this module to treeshake.

**Comment by mreinstein** [comment]
tree shaking is a neat concept not the primary goal. 

Regardless of node's support for modules, most of the popular front end bundlers (webpack, babel) do support es modules right now. Hence the proposal for `pkg.module`.

**Comment by simon04** [comment]
Closed/unsuccessful PRs: https://github.com/airbnb/polyglot.js/pull/116, https://github.com/airbnb/polyglot.js/pull/121, https://github.com/airbnb/polyglot.js/pull/127, https://github.com/airbnb/polyglot.js/pull/141, https://github.com/airbnb/polyglot.js/pull/149, https://github.com/airbnb/polyglot.js/pull/150
