### ISSUE TITLE
Readme says: "Polyglot has zero dependencies". package.json has multiple

### ISSUE THREAD

**Issue by martinlabuschin** [airbnb/polyglot.js#110]
Just installed the package and noticed that 4 other packages were installed. That surprised me since the current Readme says "Polyglot has zero dependencies". Should this sentence be removed?

**Comment by ljharb** [comment]
Oops, yes it should - having zero dependencies isn’t actually a good thing anyways, because it means wheels are likely being reinvented. Want to send a PR?

**Comment by martinlabuschin** [comment]
Created a PR: https://github.com/airbnb/polyglot.js/pull/112
