### ISSUE TITLE
Change interpolation marker

### ISSUE THREAD

**Issue by no-more** [airbnb/polyglot.js#111]
Hello,

I would like to know if it's possible to change the interpolation marker ? 
I ask that because I'm currently using another translator in my frontend which use {{...}} as the marker for interpolation and it could be great to be able to use the same on the server side (I could then share some translation more easily and it will reduce the risk of typing the wrong marker).

Thanks a lot.

**Comment by ljharb** [comment]
I believe #106 / #64 covers this.
