### ISSUE TITLE
support for AMD modules?

### ISSUE THREAD

**Issue by darewreck54** [airbnb/polyglot.js#118]
I notice when you went from 1.0 to 2.0 that the no longer supported as an AMD module?  The build folder/lib was kind of not updated at that point.  

```
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    define([], function() {
      return factory(root);
    });
  } else if (typeof exports === 'object') {
    module.exports = factory(root);
  } else {
    root.Polyglot = factory(root);
  }
}(this, function(root) {
```

as well.  Was this intended?  Didn't see that in the release notes?

**Comment by ljharb** [comment]
Yes, its “remove non-node support”. Packages should only ever be distributed as CJS - those who want to support legacy formats like AMD can use a bundler to do it transparently.
