### ISSUE TITLE
Pluralization not working in fa locale

### ISSUE THREAD

**Issue by hamidfzm** [airbnb/polyglot.js#126]
In fa locale (persian or farsi) pluralization is not working properly. For example I have following text for my i18n:
```
کاربر |||| کاربران
```
but in both plural and singular form I get *کاربر* which is the singular form.

**Comment by ljharb** [comment]
Can you share your full JS code that's using polyglot?

**Comment by hamidfzm** [comment]
I'm using it with react admin which is using polyglot for i18n. I looked at polyglot source code and I think it's because polyglot is not supporting fasi locale.

**Comment by ljharb** [comment]
@hamidfzm it should be: https://github.com/airbnb/polyglot.js/blob/master/index.js#L101 "fa" is grouped with [germanic pluralization rules](https://github.com/airbnb/polyglot.js/blob/master/index.js#L61), which, like English, have one for 1 and one for everything else.

**Comment by ljharb** [comment]
To be clear, "singular" is a plural type, so English has two: "one" and "zero or more than one". The standard seems to indicate that Farsi has two: https://www.unicode.org/cldr/charts/33/supplemental/language_plural_rules.html#fa which should mean it's working correctly.

With a specific test case, I can look more deeply into it?

**Comment by hamidfzm** [comment]
@ljharb I regenerated this issue:
```
var Polyglot = require('node-polyglot');

var polyglot = new Polyglot({locale: "fa"});

polyglot.extend({
    "num_cars": "%{smart_count} کاربر |||| %{smart_count} کاربرها",
});

console.log(polyglot.t("num_cars", {smart_count: 1}));
console.log(polyglot.t("num_cars", {smart_count: 0}));
console.log(polyglot.t("num_cars", {smart_count: 10}));
```
In all cases it prints:
```
1 کاربر
0 کاربر
10 کاربر
```

**Comment by hamidfzm** [comment]
Dear @ljharb , Thanks for great support. I figured out the problem.  React admin uses ra-core library which uses node-polyglot version 2.2.0. I used resolutions in package.json and forced ra-core to use node-polyglot version 2.3.0 and the issue is fixed. By the way, Can I ask what changed in this 2 versions?

**Comment by ljharb** [comment]
The [changelog](https://github.com/airbnb/polyglot.js/blob/master/CHANGELOG.md#v230-july-2-2018) indicates that #86 fixed this very issue.

I'd suggest filing an issue on ra-core to use `^` for their dependency on node-polyglot, which would have resolved this issue for you more easily :-)

Closing as resolved.
