### ISSUE TITLE
Docs: Fix Link to Github Repo

### ISSUE THREAD

**Issue by asapzacy** [airbnb/polyglot.js#133]
green box - takes you to https://github.com/airbnb/polyglot.js correctly
red box - takes you to https://airbnb.io/polyglot.js/ incorrectly

<img width="962" alt="Screen Shot 2019-06-27 at 10 41 07 AM" src="https://user-images.githubusercontent.com/10241031/60288241-9d36b480-98c8-11e9-98d3-5da94491121d.png">

edit - I tried pushing a fix but it failed on permissions 
```
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/airbnb/polyglot.js.git/'
```

**Comment by ljharb** [comment]
Would you be willing to make a PR?

**Comment by asapzacy** [comment]
definitely! I had one ready

**Comment by asapzacy** [comment]
@ljharb can you give me the permissions? and I'll open a PR

**Comment by ljharb** [comment]
You don’t need them; make a PR from a fork.

**Comment by flavianunes** [comment]
I sent PR for this. The link was incorrect in the README from the branches also.
