### ISSUE TITLE
Interpolation smart_count option problem

### ISSUE THREAD

**Issue by wmwart** [airbnb/polyglot.js#142]
Hello! Great library!
I had a problem translating such a line with Russian localization:

```
polyglot.extend({
  'ra.action.bulk_actions': '1 выбрано |||| %{smart_count} выбрано'
});

polyglot.t("ra.action.bulk_actions", {smart_count: 5}) ==> "1 выбрано"
```

Is this a bug or a feature? If a feature, please indicate the place in the documentation where this behavior is described.
Thanks.

  "name": "node-polyglot",
  "version": "2.4.0",

**Comment by ljharb** [comment]
I think you don't want `%1` in the phrase, you want either `%{smart_count} выбрано  |||| %{smart_count} выбрано` or `1 выбрано |||| %{smart_count} выбрано`.

**Comment by wmwart** [comment]
yes it's a typo. fix.

**Comment by ljharb** [comment]
Have you also set the locale? `polyglot.locale('ru')`, in this case?

**Comment by wmwart** [comment]
Yes.
I mentioned this problem in another library that uses Poliglot.js.  If you follow the link, there is Codesandbox, which illustrates the problem

**Comment by ljharb** [comment]
That is a very large code sandbox. Could you perhaps prepare a much smaller one, so the only library involved is polyglot? That would make it much easier to see the problem while not speaking Russian myself :-)

**Comment by wmwart** [comment]
@ljharb, [https://codesandbox.io/s/eloquent-shape-v9pe9](https://codesandbox.io/s/eloquent-shape-v9pe9)

**Comment by Sokol-ua** [comment]
Lcoale "ru" is supposed to have 3 pluralization options (PS: check source code for russianPluralGroups()):
1 рубль |||| 2 рубля |||| 5 рублей
1 сообщение |||| 2 сообщения |||| 5 сообщений
------------------- 
But you have kind of "exception" in this case, with last 2 options the same:
1 выбрано |||| 4 выбрано ||| 5 выбрано

Flow:
1. You pass smart_count: 5
2. 'ru' rule returns to use 3rd option: ||| 5 выбрано
3. But you don't have 3 option: '1 выбрано |||| %{smart_count} выбрано'
4. transformPhrase() => checks, if your string has 3 option => if don't => return first
5. You don't pass 3rd option, result => 1 выбрано


To fix you issue, I suggest to add same 3rd option:
"выбран только 1 |||| %{smart_count} выбрано |||| %{smart_count} выбрано"

That will fix you issue.

**Comment by wmwart** [comment]
@Sokol-ua, excellent thank you!

**Comment by ljharb** [comment]
Thanks, that seems the exactly correct explanation to me :-)
