### ISSUE TITLE
IE compatibility

### ISSUE THREAD

**Issue by renekliment** [airbnb/polyglot.js#144]
Hi!

We've been using your amazing library and accidentally discovered, that unfortunately it is not compatible with Internet Explorer.

The reason is the use of [for-each](https://www.npmjs.com/package/for-each) in [`.extend`](https://github.com/airbnb/polyglot.js/blob/master/index.js#L277) which [calls `isCallable`](https://github.com/Raynos/for-each/blob/master/index.js#L44).

However, [`isCallable`](https://github.com/inspect-js/is-callable/blob/master/index.js#L29) returns `false` for the `forEach` callback for some reason in IE, which causes `forEach` to `throw`.

Can't provide a quick example now as both https://codesandbox.io/ and https://stackblitz.com/ do not load under IE properly. Let me know if you need me to run an instance somewhere.

Could you please have a look at this?

**Comment by renekliment** [comment]
![Screenshot_2020-04-24_18-55-20](https://user-images.githubusercontent.com/156399/80237917-cbf2f800-865d-11ea-8fce-6595fc923699.png)

**Comment by ljharb** [comment]
`isCallable` shouldn't return false for any callback; that seems like a bug in the `is-callable` library - if you have a repro of *that*, please file it there.

This library has been working on IE 9, 10, and 11 for many many years, with is-callable, so I'm pretty confident the problem is something else in your setup.

**Comment by ljharb** [comment]
I do see, in your screenshot, that `iterator` is definitely a function. Can you debug-step into `isCallable` and determine on which line it's returning false?

**Comment by renekliment** [comment]
You're right, it seems like I have a messed up `Object.prototype.toString` polyfill somewhere causing the issue. Sorry for the inconvenience!
