### ISSUE TITLE
Please mention in the documentation `smart_count` is obligatory for pluralization to work

### ISSUE THREAD

**Issue by chepe263** [airbnb/polyglot.js#146]
Reading the documentation, `smart_count` seems like a generic name for a value that will be interpolated. People might get the idea the name for the value to be interpolated can be anything (`num_messages`, `ammo_amount`, etc) that suits the context of translation strings.

**Comment by spikebrehm** [comment]
PRs accepted :)

**Comment by chepe263** [comment]
`README.md` in master and `index.md` in gh-pages are the only places where it needs updating, right? 

I would like to know the right places before starting with the pr

**Comment by chepe263** [comment]
pr #147 for `README.md` in master branch
pr #148 for `index.md` in gh-pages branch

**Comment by ljharb** [comment]
gh-pages is only updated on release; only the master branch needs updating.

**Comment by chepe263** [comment]
the pr was merged, closing the issue...
