### ISSUE TITLE
Getting TypeError: getPolyfill is not a function after update

### ISSUE THREAD

**Issue by zakmatik** [airbnb/polyglot.js#162]
Hello!

After the latest update, I'm seeing an error in my code. It looks like the error is actually coming from `array.prototype.foreach` but seeing as you recently changed this project to use that code, I figured this is the place to report it. I've added a screenshot of the error below:

![image](https://user-images.githubusercontent.com/58279754/129634876-43665e5c-124b-436b-9136-c3d2efe6b143.png)

**Comment by ljharb** [comment]
whoops, will fix in just a second.

**Comment by ljharb** [comment]
actually, wait, that looks like it should be working just fine. `require('./polyfill')` loads https://unpkg.com/browse/array.prototype.foreach@1.0.0/polyfill.js which definitely exports a function.

**Comment by ljharb** [comment]
Is there perhaps something in your webpack or babel config that's transforming dependencies?

**Comment by zakmatik** [comment]
The project is a create-react-app project and I haven't messed with any of the webpack or babel config files. It is from a few years ago, so maybe that has something to do with it?

**Comment by ljharb** [comment]
ah, CRA does transpile node_modules. it's entirely possible that's where the issue is, but I'm not really sure - i use the pattern in array.prototype.foreach in dozens of widely used packages, and CRA's never had an issue before. Can you share your babel and webpack configs, just in case?

**Comment by zakmatik** [comment]
So I ran it on a fresh CRA install, only installing react-admin, the library that has this as a dependency. I got the same issue with a slightly different stack trace:

![image](https://user-images.githubusercontent.com/58279754/129637295-5daa412f-0ebb-4515-a2f4-4079a8ec51de.png)


Repro steps: run `create-react-app test`, run `yarn add react-admin` (or some other package that has a dependency on this), update App.js to add `import { Admin } from 'react-admin';` and then `<Admin title="test"></Admin>`.

**Comment by ljharb** [comment]
Wait, the issue doesn't appear when not using `react-admin`?

**Comment by ljharb** [comment]
Also, what do you get when you click "view compiled" on the final bit of the stack trace?

**Comment by zakmatik** [comment]
Yeah, `react-admin` is the library my app is using that depends on `node-polyglot` so I knew I'd be able to use that library to repro the issue.
Here's view compiled
![image](https://user-images.githubusercontent.com/58279754/129638184-1f239ed2-b289-40ce-bf97-bf3e69ee6914.png)

**Comment by ljharb** [comment]
I'm just very confused. Can you try removing react-admin and just installing `array.prototype.foreach`, and importing/requiring that directly?

**Comment by zakmatik** [comment]
Same error unfortunately:
![image](https://user-images.githubusercontent.com/58279754/129638573-0036e908-9037-402d-9653-084d8447e803.png)

**Comment by ljharb** [comment]
Do you get the same error if you try other es-shim packages, like `array.prototype.map` or `array.prototype.flat`? (no need to paste the screenshot if it's the same)

**Comment by zakmatik** [comment]
Requiring `array.prototype.map` and `array.prototype.flat` works

**Comment by zakmatik** [comment]
If it's helpful, the value of getPolyfill is:
![image](https://user-images.githubusercontent.com/58279754/129639991-4216c4dd-3f13-4665-bb8d-95b4c573a877.png)

**Comment by ljharb** [comment]
ohh hmm, it's pulling the ES Module. Looking into it.

**Comment by ljharb** [comment]
What version of node are you using?

**Comment by zakmatik** [comment]
node version is 12.16.3. I get the same error for string.prototype.at.

**Comment by ljharb** [comment]
That's a pretty old version of node 12 - just curious, can you try with node 12.17 or later, which is the one with ESM support? (ideally, latest 12)

**Comment by zakmatik** [comment]
I upgraded to 12.22 and then also to 14.17 and got the same error for both.

**Comment by ljharb** [comment]
Released in array.prototype.foreach v1.0.1. Does that fix it?

**Comment by zakmatik** [comment]
That did it! Thanks so much for your help!
