### ISSUE TITLE
Can this library be used with i18nexus?

### ISSUE THREAD

**Issue by saikarthikp9** [airbnb/polyglot.js#164]
[https://i18nexus.com/](https://i18nexus.com/)

Wonder if anyone is using this library along with i18nexus and how you linked them together?

**Comment by i18nexus** [comment]
@saikarthikp9 Hi! Thought we'd come in and answer this for you:

i18nexus was designed for use with i18next, but it can be used with other libraries like Polyglot as well.

i18nexus simply generates JSON files that can be downloaded by your application during runtime or build time using the i18nexus API. Once your application has your JSON translations downloaded, you can load them into Polyglot or any other i18n Javascript library. In the end, it's just JSON.

At the moment, the i18nexus UI only supports syntax highlighting for i18next and has several other i18next specific features such as pluralization and namespaces. But you can simply ignore these if you're not using i18next.

**Please reach out to us in our in-app chat and our support can hopefully guide you through it!**

FYI, we're currently in the works of extending our UI to support other i18n libraries such as Polyglot, Lingui, react-intl, etc. But at the moment you'll just have to work around the i18next-specific functionality in the UI.

**Comment by ljharb** [comment]
Thanks for answering!

I’ll close this as answered, but when such support exists, I’d love to review a PR that adds it to the readme.
