### ISSUE TITLE
Incorrect interpolation when using number prefix for Arabic content

### ISSUE THREAD

**Issue by rohitcelestial** [airbnb/polyglot.js#167]
There seems to be an issue regarding interpolation with Arabic string when template value start with a number.
```
var Polyglot = require("node-polyglot")
var polyglot = new Polyglot({interpolation: { prefix: '${', suffix: '}' }});

polyglot.extend({
  "hello_name": "الرمز ${code} غير صحيح"});

// works fine: CASE-A
polyglot.t("hello_name", {code: "De30Niro"});

// number goes at the beginning: CASE-B
polyglot.t("hello_name", {code: "30DeNiro"});
```

**Results**:
**CASE-A**:
![image](https://user-images.githubusercontent.com/7090592/162451912-ce83453a-f6ed-4339-b376-2982a5f7198d.png)

**CASE-B:**
![image](https://user-images.githubusercontent.com/7090592/162451799-2aee4a9b-1959-431a-94b2-21129b46260d.png)

**Comment by ljharb** [comment]
Thanks for the report! I'm not clear on the exact desired behavior - could you provide text of the Arabic output you *expect* from CASE-B?

**Comment by rohitcelestial** [comment]
Hi @ljharb 
Result for CASE-B: should be

![image](https://user-images.githubusercontent.com/7090592/162492140-8782b661-aa19-424d-80e8-59beb111a229.png)

**Comment by ljharb** [comment]
Could you provide that as copypasted text, instead of a screenshot? :-) i'm trying to get to the point where i can make a failing test case.

**Comment by rohitcelestial** [comment]
صحيح غير 30DeNiro  الرمز

**Comment by ljharb** [comment]
interestingly, i see the "30" next to the "DeNiro" on github, but when i copy-paste it to the test file, it moves the "30" to the front - but only visually, when i search in vim, the `30` and the `D` are actually next to each other.

**Comment by ljharb** [comment]
I wonder if the issue is just a lack of a unicode directional marker?

**Comment by rohitcelestial** [comment]
Possibly, Thinking how could get this probably encoded to avoid 30 prefix.
