### ISSUE TITLE
Feature Request: Support interpolating react nodes in transformPhrase

### ISSUE THREAD

**Issue by Xiphe** [airbnb/polyglot.js#170]
As a react developer I would like to use nested components within translations

```jsx
const p = new Polyglot({ phrases: { hello: 'Hello %{name}' } });
ReactDom.render(p.t(
  'hello',
  {
    name: <a href="https://example.org/">Example</a>
  }
))
```

(ref https://github.com/nayaabkhan/react-polyglot/issues/54, https://github.com/airbnb/polyglot.js/issues/93)

As far as i understand this is currently not possible because transformPhrase operates using [`String.prototype.replace`](https://github.com/airbnb/polyglot.js/blob/96004b2684da66f01dc13c9964620904c93b3719/index.js#L30)

If this could be customisable (by supporting `options.replace` with the same signature as `String.prototype.replace`) then we could make the t function return a react fragment or possibly other wrappers required for other interface libraries

I'll test this out and provide a PR if it works in the next days

**Comment by ljharb** [comment]
It wouldn’t be appropriate for this package to provide a react component - not the least because it adds a peer dep on react.

It’s quite possible to use polyglot as-is inside a react component; Airbnb has done so for the better part of a decade.

**Comment by Xiphe** [comment]
Thank you for the fast reaction! And sorry seems I was not clear enough about what i'm aiming at. I totally agree that this beautiful library should not tie itself to any ui framework/library or add a peer dependency. 

I just think that allowing users to customise the [`replace`](https://github.com/airbnb/polyglot.js/blob/96004b2684da66f01dc13c9964620904c93b3719/index.js#L30) implementation would make it **possible** to use _for example_ react components instead of strings when interpolating. 

I don't know what airbnb uses exactly, i've seen the [approach discussed in #93](https://github.com/airbnb/polyglot.js/issues/93#issuecomment-782290404). And I think there might be a solution that is even more elegant and comes with nearly no additional package size and just an additional option added to api complexity.

As I said I'll provide a PR in the next days I think it will make things clearer.

**Comment by Xiphe** [comment]
created the PR 💜
