### ISSUE TITLE
New Release + Updated Types

### ISSUE THREAD

**Issue by Xiphe** [airbnb/polyglot.js#173]
Hey there 👋

I've created the types for https://github.com/airbnb/polyglot.js/pull/171

Have a look here: https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...Xiphe:DefinitelyTyped:node-polyglot-custom-replace

Let me know when you plan to release this, so that I can open the PR

**Comment by Xiphe** [comment]
Hey @ljharb and @lencioni any plans to draft a polyglot release containing the latest changes?

**Comment by Xiphe** [comment]
/bump will there be a release any time soon or should we consider the project dead?

**Comment by ljharb** [comment]
@Xiphe the project isn't dead even if there's not a release any time soon. Hopefully there will be one, though.

**Comment by lencioni** [comment]
Thanks for your patience, I just published v2.5.0
