### ISSUE TITLE
Return objects or arrays 

### ISSUE THREAD

**Issue by yertech** [airbnb/polyglot.js#175]
Hello,

Is there any code to return objects or arrays from a key like this : 
https://www.i18next.com/translation-function/objects-and-arrays
```
{
    "tree": {
        "res": "added {{something}}"
    },
    "array": ['a', 'b', 'c']
}

t('array', { returnObjects: true });
=> ['a', 'b', 'c']
```

Thanks

**Comment by ljharb** [comment]
This seems to have been opened on the wrong repo? If not, then I’m not clear on the ask.
