### ISSUE TITLE
Polyglot on Backbone Structure

### ISSUE THREAD

**Issue by guilhermeccrz** [airbnb/polyglot.js#20]
Guys, i have a large project. The Backend will send me a JSON DATA with all translations, in my bb structure how should be my structure with polyglot? what is the best way? put polyglot on a backbone view? or in a general model? Any tips? Thx :dancers:

**Comment by sofer-eg** [comment]
I use this way: before some render load phrases in locale model like this
```
    var LocaleModel = Backbone.Model.extend({
        defaults: {
            phrases: [],
        },
        initialize : function(models, options) {},
        url : function() {
            return '/locales/' + this.get('id') + '.json';
        },
    });
```
Then just create polyglot object and load phrases from model
```
var polyglot = new Polyglot({locale: browserLocale});
polyglot.extend(localeModel.get('phrases'));
```
and then use polyglot.t('phraseName') where it need.
