### ISSUE TITLE
server rendering example?

### ISSUE THREAD

**Issue by lifeiscontent** [airbnb/polyglot.js#25]
Could you give an example on how to use this to render server side?

I assume you guys are doing it at AirBnB?

**Comment by goatslacker** [comment]
It doesn't vary from the example on the README there's just a bit more glue involved depending on what you're trying to do.

In a nutshell:

Instantiate it

```
var polyglot = new Polyglot();
```

Add phrases to it

```
polyglot.extend({
  "hello": "Hello!"
});
```

Use it

```
polyglot.t("hello")
```

**Comment by brakon** [comment]
this doesnt seem like an accurate example, it fails to say:
* how to initially an existing dictionary (or dictionaries) for different locales.
* if we are supposed to initialize the dictionary in each request, looks like it since extend the dictionary with the new Polyglot() instance, so every request will have an empty polyglot dictionary that it needs to populate.
* How to configure the supported locales

**Comment by bitinn** [comment]
I am not from Airbnb but think this approach help on server-side (node.js). Say you are writing a middleware for koa.

1. use `.extend(languageFile, prefix)` to load ALL of your translations into locale specific prefix, eg. `.extend(chineseTranslation, 'zh')`, do this in local scope of your middleware, so you only load them once, not per request.

2. pass the local polyglot object to downstream like `this.state.i18n = polyglot`

3. in your downstream middleware, use the translation according to your request's locale settings, eg. if you do subdomain translation, figure it out from `this.subdomains`, then load translation like `i18n.t(prefix + 'my.translation.name')`

4. you can write a helper middleware that do the `.t(prefix + 'name')` part for convenience, again extend koa `this` with something like `this.i18n`.

Hopefully it helps.

I assume this is how you guys do it? @goatslacker @spikebrehm

**Comment by spikebrehm** [comment]
We do something similar to @bitinn in Express, using a middleware:

```js
app.use(function(req, res, next) {
  req.polyglot = new Polyglot();
  
  var locale = determineLocaleFromRequest(req);

  getPhrasesForLocale(locale, function(err, phrases) {
    if (err) return next(err);
    req.polyglot.extend(phrases);
    next();
  });
});

function determineLocaleFromRequest(req) {
  // Look at i.e. subdomain, path to determine locale
  return 'de';
}

function getPhrasesForLocale(locale, callback) {
  // Fetch phrases, perhaps using a REST api or reading a config file
  // do something async...
  callback(null, phrases);
}
```

**Comment by siboulet** [comment]
Sorry for reviving this old issue but I couldn't find another Express example. Doesn't the example above cause the language file (phrases) to be loaded on EACH request? If I get this right if one wants to do caching of the language file she has to do this herself in the middleware?

It's not possible to load the language files (phrases) into Polyglot once (ie. initializing Polyglot with the languages file on app start)? Each Polyglot *instance* (per request) needs to be extended with the phrases to be used by the instance?

**Comment by ljharb** [comment]
Each request might have a different locale, so I'm not sure how else you'd do it. Of course you can cache different instances-per-locale, and fetch the one you want per request, and if you `require` JSON files, node will cache those for you in the require cache, etc - but you always need to change the available phrases for each request somehow.

**Comment by siboulet** [comment]
@ljharb thanks for pointing out the `require` method which would use the node cache. However currently we use YAML files so thats not an option for us. 

I understand each request get its own Polyglot instance with its own locale. I'm just a bit surprised there is no way to load the phrases in the global scope of the Polyglot module somehow and just have each instance switch between the definitions.

**Comment by ljharb** [comment]
That would be additional complexity in polyglot, for something that's trivial to achieve on your own. You could clear and extend the same instance, and cache phrase objects; you could prepare multiple instances and cache them, using the appropriate one; there's lots of solutions.

**Comment by spikebrehm** [comment]
> I'm just a bit surprised there is no way to load the phrases in the global scope of the Polyglot module somehow and just have each instance switch between the definitions.

Like @ljharb said, that's something you can implement easily in your app, i.e. by having a map of locales to phrases stored in a variable.  Instantiating a `new Polyglot(phrases)` on each request doesn't mean you can't cache those phrases somewhere else.

```js
// server.js

const phrasesByLocale = {
  en: { ... },
  fr: { ... },
  zh: { ... },
};

app.use(function(req, res, next) {
  const locale = determineLocaleFromRequest(req);
  const phrases = phrasesByLocale[locale];
  req.polyglot = new Polyglot(phrases);
  next();
}
```

**Comment by israelmuca** [comment]
> @ljharb thanks for pointing out the `require` method which would use the node cache. However currently we use YAML files so thats not an option for us.
> 
> I understand each request get its own Polyglot instance with its own locale. I'm just a bit surprised there is no way to load the phrases in the global scope of the Polyglot module somehow and just have each instance switch between the definitions.

If anyone wants an express example, here's one I made (by using parts of what @spikebrehm posted)

## First, I create the actual language phrases:
```javascript
//lang.js
export const lang = {
    es: {
        '404': ' no existe o espera otro método HTTP.'
    },
    en: {
        '404': ' does not exist or expects another HTTP method.'
    }
}
```

### Then, I create a middleware function for Express to get those
```javascript
//setLocale
import Polyglot from 'node-polyglot'
import { lang } from '../lang/lang'

exports.startPolyglot = (req, res, next) => {
    
    // Get the locale from express-locale
    const locale = req.locale.language
    console.log(locale)

    // Start Polyglot and add it to the req
    req.polyglot = new Polyglot()

    // Decide which phrases for polyglot
    let phrases
    if (locale == 'es') {
        phrases = lang.es
    } else {
        phrases = lang.en
    }

    // Add the actual phrases to polyglot and call next()
    req.polyglot.extend(phrases)
    next()
}
```

### Finally, I import that in the server.js
```javascript
//server.js
import createLocaleMiddleware from 'express-locale'
import { startPolyglot } from './utilities/setLocale'
...
app.use(createLocaleMiddleware({
    "priority": ["accept-language", "default"],
    "default": "en_US"
}))
app.use(startPolyglot)
```

And that's it!
