### ISSUE TITLE
Number values are not longer supported in 0.4.2

### ISSUE THREAD

**Issue by outaTiME** [airbnb/polyglot.js#28]
Hi guys, 

Today i update the polyglot version to 0.4.2 and start failing to resolve my keys. i go back to 0.4.1 version and all goes fine.

**Comment by outaTiME** [comment]
Yup apparently number values are not longer supported any other translations are supported

**Comment by outaTiME** [comment]
Take a look, the following example:

```js
var polyglot = new Polyglot();
polyglot.extend({
  "number": 1, 
  "number_str": "1",
});
polyglot.t('number'); // WARNING: Missing translation for key: "number"
polyglot.t('number_str'); // "1"
```

In version 0.4.1 number values as translation are supported, please today it issue breaks my production environment

**Comment by outaTiME** [comment]
Same with 0.4.3 version, not yet solved :sob:

**Comment by justjake** [comment]
Hello. Would coercing all texts in the object passed to `.extend` to strings be acceptable?

**Comment by outaTiME** [comment]
Sorry, i don't understand ... could you clarify please ... 

thks !

**Comment by justjake** [comment]
Polyglot assumes that if a translation value is defined, then it is a string: https://github.com/airbnb/polyglot.js/blob/master/lib/polyglot.js#L170

I can either change Polyglot so that (a) all phrases are cast to strings, or (b) any type of value may be used as a phrase.

(a):
```
var polyglot = new Polyglot();
polyglot.extend({
  "foo": 1, 
});
polyglot.t('foo'); // --> "1"
```

(b)
```
var polyglot = new Polyglot();
polyglot.extend({
  "foo": 1, 
  "bar": null,
});
polyglot.t('foo'); // --> 1
polyglot.t('bar'); // --> null
polyglot.t('bar', { allowEmpty: true }); // --> null
```

**Comment by ljharb** [comment]
What would be the use cases for having a non-string phrase?

I can imagine some sort of smart pluralization thing using an object as a phrase, and selecting the desired string from that object later, but that might be overthinking it.

**Comment by justjake** [comment]
we could do something like this [1] to allow numeric phrases, but I think it would be better to enforce numeric phrases with an assertion in `extend`, and that @outaTiME should change his usage of Polyglot.

At Airbnb, we only use string phrases, and that is what this library is designed around. 

[1]: https://github.com/airbnb/polyglot.js/compare/master...justjake:allow-numeric-phrases?expand=1

**Comment by outaTiME** [comment]
How would it be to enforce numeric phrases with an assertion in "extend" ??

I need to update my number phrases to strings ??

**Comment by outaTiME** [comment]
You PR are fine, or not ?

**Comment by outaTiME** [comment]
I think a valid JSON may be used as translation table, no complex object allowed but simple types like package.son or something else.

**Comment by ljharb** [comment]
Closing this - phrases are strings.

Our apologies for having a breaking change in a sub-1.0 patch version (instead of a minor).

By now we're up to v2.0.0 so hopefully you've upgraded :-)
