### ISSUE TITLE
Using *.po files or another structures as data source for translation?

### ISSUE THREAD

**Issue by DeadByElpy** [airbnb/polyglot.js#30]
Do you plan to add method for loading texts from translation files (like .po), into Polyglot? Maybe, some libraries, plugins are exists for this? Can you tell me what method you used in Airbnb, ofcourse, if it not a secret.

**Comment by justjake** [comment]
We don't use such files at Airbnb. Our translation system uses a backing database which we query to get our translations

**Comment by ljharb** [comment]
A PR that makes using PO files easier, without impacting our primary use case, would be welcome. In the meantime, closing this.
