### ISSUE TITLE
Return false when a translation is not found and allowMissing is set to false

### ISSUE THREAD

**Issue by limoragni** [airbnb/polyglot.js#34]
I'm using polyglot for translating dynamically generated strings and I would like to have a way of knowing when a translation is not available. 

For what I saw in the code the allowMissing just pass the string to the choosePluralForm and interpolate methods. But if allowMissing is false, it just returns the key used for the translation. The keys I'm using are in some cases numerical codes that refers to strings in different languages, so having the key back breaks my code silently. 

```
   if (typeof this.phrases[key] === 'string') {
      phrase = this.phrases[key];
    } else if (typeof options._ === 'string') {
      phrase = options._;
    } else if (this.allowMissing) {
      phrase = key;
    } else {
      this.warn('Missing translation for key: "'+key+'"');
      result = key;
    }
    if (typeof phrase === 'string') {
      options = clone(options);
      result = choosePluralForm(phrase, this.currentLocale, options.smart_count);
      result = interpolate(result, options);
    }
    return result;
```

Apart for the warning I think that result should be false. What do you think?

**Comment by ljharb** [comment]
That seems reasonable, but would be a breaking change. What about adding an alternative option that returns `undefined` or `false` or something?

**Comment by limoragni** [comment]
An option like allowMissing but returning false/undefined when there is no matches? I think that would be enough.

**Comment by pleivac** [comment]
Is there any way to achieve this? I'm thinking something like `if(polyglot.t("key") === "key")` the translation doesn't exists. But this solution is really ugly, and not work all the time for me.

**Comment by ljharb** [comment]
@pleivac you can use `polyglot.has(key)` to determine if the phrase is present or not.

**Comment by pleivac** [comment]
Perfect @ljharb... Many many thanks!

**Comment by ljharb** [comment]
@limoragni @pleivac I've filed #77 to address this in a more generic manner. Please let me know if that will resolve your use cases.

**Comment by limoragni** [comment]
@ljharb yes, I think onMissingKey is a great solution!
