### ISSUE TITLE
testing on travis/circle or other CI service

### ISSUE THREAD

**Issue by PeterDaveHello** [airbnb/polyglot.js#39]
Hi there, would you consider to put this project to run the CI testing online? So that we can make sure all the PRs passed the test before merged! :smile:

**Comment by ljharb** [comment]
That's a great idea - we should definitely add a `.travis.yml`. I'll take a look at this within the next week or so.

**Comment by PeterDaveHello** [comment]
Created here: https://github.com/airbnb/polyglot.js/pull/40
