### ISSUE TITLE
Is there any working example with React and Redux?

### ISSUE THREAD

**Issue by dbertella** [airbnb/polyglot.js#47]
Is there any working example with React and Redux? It'll be really helpful to see this in action

**Comment by mrakowski0** [comment]
I'm using it right now on production. What exactly is special about React+Redux in this library's context?

**Comment by dbertella** [comment]
I was looking to localize an app that I'm working on and I'm still looking at a good solution. I'd like to know if you implement the logic it in components or you are using actions and reducers some how. You have a single source for translation or different classes with small pieces of translations?

**Comment by ljharb** [comment]
polyglot is constructable - you'd either have a singleton instance for your whole app, or you could create as many instances of it as you need to separate phrase groups.

**Comment by Vadorequest** [comment]
Here is how I used it in React/Redux, implemented yesterday. 

I18nService.cjsx
```cjsx
React = require 'react'
Polyglot = require 'node-polyglot'

currentLocale = 'en'
locales =
    fr: require './../locales/fr'
    en: require './../locales/en'

class I18nService

    initialize: (options) ->
        @i18n = new Polyglot options

polyglot = (new I18nService).initialize({
    locale: "#{currentLocale}"
    phrases: locales[currentLocale]
})

module.exports = polyglot
```

Mixins relies on the npm `react-mixin` library. https://www.npmjs.com/package/react-mixin

i18nMixin.cjsx
```cjsx
React = require 'react'
I18nService = require './../services/I18nService'

showMixin =
    propTypes:
        i18n: React.PropTypes.object.isRequired
        t: React.PropTypes.func.isRequired

    getDefaultProps: ->
        i18n: I18nService
        t: -> I18nService.t.apply(I18nService, arguments)# "translate()" alias

module.exports = showMixin
```

`./locales/en`:
```coffee
phrases =
    insert_text: 'Add Text'
    insert_h1: 'Add Heading 1'
    options: 'Options'
    editor:
        insert_block: 'Insert a new block there'

        pattern:
            move_up: 'Move up'
            move_down: 'Move down'

module.exports = phrases
```

Exemple of use
```cjsx
{ applyMixin, classNameMixin, styleMixin, i18nMixin } = require '../../mixins/index'

class Icon extends React.Component
    render: ->
        <i
            className={@getClasses()}
            title={@props.t(@props.label)}# HERE -> if @props.label is "insert_text" then displays "Add text"
            style={@props.style}
            onClick={@props.onClick?.bind(this)}
        >
            <span style={'paddingLeft': '1px'}>{@props.children}</span>
        </i>

applyMixin.onClass Icon, classNameMixin
applyMixin.onClass Icon, styleMixin
applyMixin.onClass Icon, i18nMixin
module.exports = Icon
```

Hope it helps.

**Comment by guillaumearm** [comment]
Hi all,
thanks for Polyglot.js, this module is awesome.

you can see an example of implementation with Redux in this module : [redux-polyglot](https://github.com/Tiqa/redux-polyglot).
There's also an enhancer for React components [here](https://github.com/Tiqa/redux-polyglot/blob/master/src/translate.js).

[PRs open](https://github.com/Tiqa/redux-polyglot/blob/master/CONTRIBUTING.md).
