### ISSUE TITLE
v2 browser support?

### ISSUE THREAD

**Issue by antpaw** [airbnb/polyglot.js#55]
[Breaking] Remove non-node support + use object.assign/for-each.

does it mean the library can no longer be used in the browser?
If the answer is yes, can you tell me what are the reasons to drop the support?

Thanks

**Comment by ljharb** [comment]
Nope! It just means you'd use `browserify` or `webpack` or a similar tool to use it in the browser. Modern web dev requires using a module system and a build process, and individual modules don't need to handle that complexity.

**Comment by antpaw** [comment]
okay cool, is there a list of browsers v2 supports?

**Comment by ljharb** [comment]
@antpaw it continues to support everything. If you find a browser it doesn't work in, please file an issue.

**Comment by antpaw** [comment]
okay thanks, will do.
