### ISSUE TITLE
Improve the warning messages

### ISSUE THREAD

**Issue by oliviertassinari** [airbnb/polyglot.js#56]
I believe the warning implementation. I see two issues with how it's done [now](https://github.com/airbnb/polyglot.js/blob/c2985d7fe94b884dd1deb9cc4532a165c70bbb44/index.js#L301-L305).
```js
function warn(message) {
  if (typeof console !== 'undefined' && typeof console.warn === 'function') {
    console.warn('WARNING: ' + message);
  }
}
```
1. Using `console.warn` isn't providing the stack trace and make debugging hard.
2. We end up with the dev checks in the production build. That some wasted bytes.

To solve those two issues, what do you think about?

1. https://github.com/r3dm/warning (use `console.error` internally)
2. https://github.com/oliviertassinari/babel-plugin-transform-dev-warning (make dead code removal possible)

**Comment by ljharb** [comment]
hmm - it wouldn't be a warning if it used "error", it'd be an error.

I'd be open to using a module like `warning`, however.

**Comment by ljharb** [comment]
@oliviertassinari babel doesn't transpile node_modules by default - how would consumers be able to use that babel transform to remove the warning() call?

**Comment by oliviertassinari** [comment]
They won't. On the Material-UI repository, we transpile the source code before publishing to npm.
We could do the same here.

**Comment by ljharb** [comment]
Sure, but then in a reusable module, when would the dead code ever be eliminated? Either it would ship without the warning in every case, or, with the `process.env` check in every case.

**Comment by oliviertassinari** [comment]
Well, the source code would
- contain:
```jsx
warning(false, `don't do this`);
```
- be published to npm like this for users:
```jsx
if (process.env.NODE_ENV !== 'production') {
  warning(false, `don't do this`);
}
```
- be used in development by users like this:
```jsx
if (process.env.NODE_ENV !== 'production') {
  warning(false, `don't do this`);
}
```

Then, it's the responsibility of users to set `process.env.NODE_ENV = 'production'`.
If later, they minify the source code, the *if statement* will be removed.

**Comment by ljharb** [comment]
That works for React itself because they provide a pre-minified production build - which is an edge case. Reusable modules shouldn't provide builds. The if statement *won't* be removed unless they're applying babel transforms to node_modules - which also shouldn't be done.

**Comment by ljharb** [comment]
I don't mind using `warning` - but I don't think there's any value wrt dead code removal, both since this module won't be providing a build file, and since consumers don't/shouldn't be transforming third-party code.

**Comment by oliviertassinari** [comment]
> The if statement won't be removed unless they're applying babel transforms to node_modules 

I don't get it. As far as I know. Many people use webpack or browserify built in tools and not babel to replace the `process.env.NODE_ENV`

> which also shouldn't be done.

I think that It depends on the environment. Most people don't let babel parse the `node_modules` to seed up the processus. But in the production environement, applying something like https://github.com/thejameskyle/babel-react-optimize to the `node_modules` could be better.

**Comment by ljharb** [comment]
You specifically mentioned `babel-plugin-transform-dev-warning` - perhaps that's confusing the issue, since env-specific babel transforms, as we've said, only apply to top-level apps.

I agree that people using browserify/webpack may be doing inlining `NODE_ENV` checks on their entire build. That would indeed cause `warning` to be a noop.

I'll make this change.

**Comment by oliviertassinari** [comment]
@ljharb Thanks, now we get an `console.error` instead of a `console.warning` :).

Regarding dead code removal, that won't work at 100% as `warning` is wrapped by `warn`.
Notice that react-router is applying the babel transform before publishing to npm https://github.com/reactjs/react-router/blob/master/.babelrc
