### ISSUE TITLE
polyglot only download needed language. 

### ISSUE THREAD

**Issue by julianmartinezmansell** [airbnb/polyglot.js#57]
Hi, is it posible to use polyglot.js but not load all language files with webpack. I want to be able to only load one language "en.json" and not load the rest. That way it keeps the download smaller. Would it also work on server/nodejs and client?
Thaks.

**Comment by ljharb** [comment]
Your language file implementation, and especially your browserify/webpack config, is intentionally independent of this library - I'm sure there's a way it can work, but that will depend on what you have set up.
