### ISSUE TITLE
Considering adding a related projects section

### ISSUE THREAD

**Issue by oliviertassinari** [airbnb/polyglot.js#58]
Hi,

I'm working on a tool that **statically analyse** the source code in order to check the health of the localization: [i18n-extract](https://github.com/oliviertassinari/i18n-extract).
I have added an [example](https://github.com/oliviertassinari/i18n-extract/blob/master/examples/polyglot.js) that works well with this project.
Can I submit a pull request that add a new section under the [README.md](https://github.com/airbnb/polyglot.js/blob/master/README.md) for _related projects_?

**Comment by ljharb** [comment]
Sure!
