### ISSUE TITLE
Can't resolve module 'fs' when compiling with webpack?

### ISSUE THREAD

**Issue by EdwardDrapkin** [airbnb/polyglot.js#63]
When I try to use polyglot with webpack, I get this error from webpack:

ERROR in ./~/polyglot/i18n.js
Module not found: Error: Can't resolve 'fs' in 'node_modules/polyglot'
 @ ./~/polyglot/i18n.js 9:7-20

What am I doing wrong? My code is only:

`import Polyglot from 'polyglot';`
`const p = new Polyglot();`

**Comment by ljharb** [comment]
fs can't possibly work in a browser, so there'd be no point browserifying/webpacking something that requires it.
