### ISSUE TITLE
Compilation depends upon Browserify

### ISSUE THREAD

**Issue by adamhooper** [airbnb/polyglot.js#73]
I tried using Polyglot in a non-Browserify/Webpack environment. I ran into the following problems:
- Dependencies on for-each, has and object.assign led to code bloat.
- The dependency on [warning](https://github.com/BerkeleyTrue/warning) broke the build because ... erm ... "warning" depends upon Browserify.

Since each function serves a _tiny_ purpose, I worked around those problems in https://github.com/adamhooper/polyglot.js/tree/for-decision-2016. Surely I'm not the only one who experiences these problems. Would you consider a pull request?

**Comment by ljharb** [comment]
Compilation of the majority of the JS ecosystem requires browserify and/or webpack - that's the nature of JS in 2016.

It is a hugely best practice to require consumers use browserify/webpack/etc, and a very bad idea to enable people to hurt themselves by not using it, by providing them with workarounds.

**Comment by ljharb** [comment]
In other words, a "non-Browserify/Webpack environment" is obsolete, and is best served by becoming one.
