### ISSUE TITLE
Error thrown with undefined option

### ISSUE THREAD

**Issue by oliviertassinari** [airbnb/polyglot.js#79]
Let's take the following code 
```js
polyglot.t('snackbar_error', { message })
```
and the following key:
```js
snackbar_error: 'Erreur : %{message}',
```

It's gonna output `Erreur : foo` when `message = foo`
But when `message = undefined` it's throwing [here](https://github.com/airbnb/polyglot.js/blob/master/index.js#L145):
> TypeError: String.prototype.replace called on null or undefined

I think that it would be better not to crash and to display a warning in the console so we save time digging into it.

**Comment by oliviertassinari** [comment]
Actually, it's most likely a regression. I have some new errors in production link to this since the latest release.

**Comment by ljharb** [comment]
Indeed, this works in v2.0.0 and is broken in v2.1.0. It seems that I broke it in 4e6fcf80a4286f27cce632dcd39a99584a9cbd2f - I'll get a v2.1.1 out that fixes it ASAP.

**Comment by ljharb** [comment]
v2.1.1 published with the fix. Thanks for the report!

**Comment by klaemo** [comment]
This change introduces different behavior than in `2.0.0`.

It used to be that `t('snackbar_error', { message })` with undefined message, would return `'Erreur : %{message}'` (with the expression still included). Now the expression gets replaced with an empty string.

This could be considered breaking, at least it broke a bunch of tests for us.

**Comment by ljharb** [comment]
Thanks, I'll get a fix out asap.

**Comment by ljharb** [comment]
It's unfortunate that `null` and `undefined` have different behavior than "absent" - that may need to be corrected in v3.

**Comment by ljharb** [comment]
v2.1.2 and v2.2.1 published with the fix.

**Comment by klaemo** [comment]
Thanks so much for the quick fix! ❤
