### ISSUE TITLE
Plural types

### ISSUE THREAD

**Issue by elGatoMantocko** [airbnb/polyglot.js#80]
Hey guys. Was wondering the proper use of pluralization for this library. It appears that the pluralization types are a bit off. I am wondering if this is something that could be merged in with a PR or if I should fork and use my own.

eg. French differentiates between 0, 1, and 2+. Czech differentiates between 1, 2, 3, 4, 5+.

These types don't quite line up with the plural types object that you have built in this library.

Thanks,

Elliott

**Comment by ljharb** [comment]
Can you provide some examples?

http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html#cs suggests that Czech does not in fact distinguish between 2, 3, and 4, for example, and similarly http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html#fr does not imply that 0 and 1 are distinguished in French.

**Comment by xpepermint** [comment]
I need to add [SL](http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html#sl) locale.

**Comment by ljharb** [comment]
@xpepermint thanks, PRs (with docs, tests, and citations) welcome :-)

**Comment by ljharb** [comment]
I believe the next release will include Slovenian (#113); Czech and French are correct already. Closing.
