### ISSUE TITLE
Error with 'fs'

### ISSUE THREAD

**Issue by carvalhoviniciusluiz** [airbnb/polyglot.js#81]
Hi,
In a project when i use Webpack of this error:

`
ERROR in ./~/polyglot/i18n.js
Module not found: Error: Cannot resolve module 'fs' in ~/form-builder/node_modules/polyglot
 @ ./~/polyglot/i18n.js 9:7-20
`

How do you solve this?
Thanks!

**Comment by ljharb** [comment]
`polyglot` is a different module - this is `node-polyglot`.
