### ISSUE TITLE
Old changelog on website

### ISSUE THREAD

**Issue by jmm** [airbnb/polyglot.js#82]
Wanted to give you a heads up in case you don't know that the changelog displayed on the website stops at v0.4.0: May 22, 2014.

**Comment by ljharb** [comment]
Thanks! This should now be updated.

**Comment by jmm** [comment]
Thanks! I see there's now a [History](http://airbnb.io/polyglot.js/CHANGELOG.md) link, but FYI I'm getting 404.

**Comment by ljharb** [comment]
Try now (altho I'd recommend looking at the repo directly for the changelog)

**Comment by jmm** [comment]
It loads now, although it's raw markdown. Yeah, that's what I ended up doing -- I mostly mentioned it as a courtesy since it could give the impression the lib is unmaintained. For that matter you could just link to it on GH if you want, no?

**Comment by ljharb** [comment]
Due to the automated process that generates that site, we'd have to hardcode the changelog markdown link in the readme, which would be unfortunate. I could certainly update that in-place, but it'd be erased once the docs were updated.

**Comment by jmm** [comment]
Oh, I see. Well like I said, I can definitely just read it on GH and just wanted to give you a heads up.
