### ISSUE TITLE
polyglot.js for my app on Google App Engine

### ISSUE THREAD

**Issue by SouthDownsTechnologySolutions** [airbnb/polyglot.js#87]
Recently we tried to implement React.js on Google App Engine and we encountered problems so we stopped the move to React.js. Now we build our application and we were looking for solutions to localize (translation to other languages) and we find polyglot.js. Then we studied the polyglot and we found Polyglot is in React JS. My question is simple, can we use the Polyglot.js without React.js and if yes then how? Regards, Green.

**Comment by ljharb** [comment]
Polyglot isn't in React; you can use it with anything.

Polyglot takes a hash of keys to phrases, and then when given a key, gives you the phrase. It should work with any backend and any frontend.
