### ISSUE TITLE
is it possible to declare multiple locales inside the config?

### ISSUE THREAD

**Issue by nodirashidov** [airbnb/polyglot.js#88]
My current config for polyglot is as follows:
```
import localeFile from './locales/ja';
import Polyglot from 'node-polyglot';

const polyglot = new Polyglot(
  {
    phrases: localeFile
  }
);

export default class I18n {
  __(key) {
    return polyglot.t(key);
  }
}
```
As you can see I am importing a single locale. It would be great if I could import all locales and then based on the locale parameter, use the needed resource. Obviously polyglot does not have the resource() method, but I was wondering if there is any way I can achieve what I want with Polyglot.

```
import resourceEn from './locales/en';
import resourceRu from './locales/ru';
import resourceJa from './locales/ja';
```
And then add a constructor() like this:

```
  constructor(locale="en") {
    polyglot.resources({
      en: resourceEn,
      ru: resourceRu,
      ja: resourceJa
    });
    polyglot.locale(locale);
  }
```
And then I use the specified locale
Thank you!

**Comment by ljharb** [comment]
You can, but the common best practice is to only ever ship data for a single locale to the browser, so as to keep page weight small.

You could, however, do:
```js
export default class I18n {
  constructor(locale = "en") {
    this.polyglot = {
      en: new Polyglot({ phrases: resourceEn, locale: 'en' }),
      ru: new Polyglot({ phrases: resourceRu, locale: 'ru' }),
      ja: new Polyglot({ phrases: resourceJa, locale: 'ja' }),
    }[locale];
  }

  __(key) {
    return this.polyglot.t(key);
  }
}
```

**Comment by nodirashidov** [comment]
Thank you!!! I am hitting my head on the wall for not thinking of this! I am using polyglot for a google apps script project, so no browser is involved here. All .js files are combined into one and uploaded to GAS. Thank you!
