### ISSUE TITLE
HTML as parameter

### ISSUE THREAD

**Issue by szabolcsx** [airbnb/polyglot.js#89]
Hi,

Is it possible to use HTML elements like `<a>` as parameter value?

Here is an example of what I am thinking:

``` json
{
    "termsOfUse": "Terms of Use",
    "iAcceptWhat": "I accept the %{what}"
}
``` 
``` javascript
polyglot.t("iAcceptWhat", { what: `<a href="${link}">${polyglot.t("termsOfUse")}</a>` })
```

Right now everything is returned as plain text, even the HTML code.
What I need is a text followed by another portion of text wrapped inside `<a>` tags.
``` HTML
I accept the <a href="#">Terms of User</a>
```

**Comment by ljharb** [comment]
I'm confused; what format would you want it to return that's not a string?

**Comment by szabolcsx** [comment]
One thing I forgot to mention is that I'm using it with React. I guess cases like this one require the use of `dangerouslySetInnerHTML`

**Comment by ljharb** [comment]
Yes - internally at Airbnb we have a component that safely builds up the HTML string; otherwise it has to use `dangerouslySetInnerHTML`.

Regardless it's not something polyglot should be solving; you should pass the string you get from polyglot into something else :-)
