### ISSUE TITLE
Use in DOM

### ISSUE THREAD

**Issue by nise** [airbnb/polyglot.js#90]
Maybe I misunderstand the purpose of polyglot.js, but how can I address DOM-elements directly?
Lets say I have tag like `<div id="foo"></div>` that should contain the text "bar". 

The jquery i18n library provides a way to use data-attributes like `<div data-i18n=”foo”></div>` in order to fill in the values for each key.

**Comment by ljharb** [comment]
This library doesn't solve those problems for you; you'd need to do the DOM interaction yourself.

**Comment by FabricioRHS** [comment]
Hi @nise, you can use jquery for help  in the task, sample:

```js
$('[data-i18n]').each(function () {
	var valueKey = $(this).data('i18n');
	if (valueKey != "") {
		var valueTranslate = polyglot.t(valueKey);
		$(this).html(valueTranslate);
	}
});
```
for more details: https://jsfiddle.net/fabriciorhs/hfqx92eq/

This PolyglotJS helps me a lot!
